GET http://localhost:3002/accounts


###
GET http://localhost:3002/accounts/12

###

POST  http://localhost:3002/accounts  
Content-Type: application/json

{
    "userName": "vlogganesh1",
    "firstName": "Venkatakrishnan",
    "secondName": "Logganesh",
    "emailId": "satiyam94@gmail.com",
    "password": "abcd1234",
    "Phone": "92392913"
}





